### ISSUE TITLE
Clarify README

### ISSUE THREAD

**Issue by ccmmgg** [MirageNet/ObjectPooler#6]
Regarding this section in README:

https://github.com/MirageNet/ObjectPooler/blob/cc6421cdfad0bc886ddcfaaf581b8c5a08725b68/README.md?plain=1#L24-L25

Is "network object where all other mirage components are" referring to the big NetworkManager object or the object that would be calling the pool manager--the player, for instance?

**Comment by dragonslaya84** [comment]
Yes atttach it to where network manager and network scene manager character spawner etc is

**Comment by ccmmgg** [comment]
Thank you for the info. I found the discord and will ask simple questions there next time.
